In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import time

In [10]:
df2 = pd.read_csv('Dart_codelist_last30_2.csv', usecols = ['종목명','종목코드','기업코드','수정일'], converters={'종목코드':str,'기업코드':str})
# 상장회사 목록

# usecols 뽑을 데이터 지정하는 코드, converters 종목코드 str으로 바꿔주는 코드

#종목코드 앞자리가 0이므로 스트링으로 지정해주지않으면 0이 사라짐
df2

              종목명    종목코드      기업코드       수정일
0          지놈앤컴퍼니  314130  01276026  20210216
1              웹젠  069080  00405320  20210215
2             우리넷  115440  00664048  20210217
3         마이크로디지탈  305090  01267967  20210217
4              나노  187790  00994994  20210216
5             손오공  066910  00306870  20210216
6            새로닉스  042600  00147994  20210217
7           피씨디렉트  051380  00297934  20210217
8             이큐셀  160600  00818472  20210125
9           케이엠제약  225430  01095704  20210126
10         교보9호스팩  331520  01398151  20210126
11         네추럴FNP  086220  00523176  20210217
12           로보로보  215100  01063990  20210217
13          DSR제강  069730  00151298  20210215
14    교보10호기업인수목적  355150  01476219  20210126
15          아이비김영  339950  01414422  20210217
16        메디안디노스틱  233250  01035942  20210215
17       미래에셋맵스리츠  357250  01437292  20210127
18         한국정밀기계  101680  00257732  20210128
19            비비씨  318410  01153105  20210217
20             삼기  122350  00799177  20210217
21         씨앤에스링크  245450  01116380  20210217
22          유나이티드  033270  00158963  20210215
23           지니언스  263860  00962223  20210215
24            파라텍  033540  00105138  20210105
25         예스코홀딩스  015360  00105101  20210105
26           시노펙스  025320  00203023  20210105
27           모나리자  012690  00173102  20210215
28         티웨이홀딩스  004870  00109514  20210215
29        씨앤지하이테크  264660  00605328  20210215
...           ...     ...       ...       ...
1945         맘스터치  220630  01089855  20210511
1946           대교  019680  00108913  20210512
1947         동국제강  001230  00114792  20210512
1948          모아텍  033200  00241209  20210513
1949          아리온  058220  00441128  20210611
1950           GV  045890  00455112  20210611
1951      SGA솔루션즈  184230  00988364  20210611
1952         아이엠텍  226350  00809517  20210611
1953         엘비루셈  376190  00527011  20210611
1954        한화솔루션  009830  00162461  20210503
1955       한국조선해양  009540  00164830  20210506
1956           라임  065160  00389387  20210512
1957         제주은행  006220  00148832  20210512
1958         신화실업  001770  00137809  20210503
1959           대원  007680  00111838  20210601
1960      제이씨현시스템  033320  00223513  20210601
1961        한솔홀딩스  004150  00171636  20210601
1962     이베스트투자증권  078020  00330424  20210601
1963       롯데하이마트  071840  00158307  20210602
1964       SM C&C  048550  00185046  20210602
1965       한국전력공사  015760  00159193  20210602
1966        상지카일룸  042940  00232007  20210602
1967       AJ네트웍스  095570  00365387  20210513
1968      한국코퍼레이션  050540  00302078  20210513
1969       KB손해보험  002550  00120216  20210513
1970          컨버즈  109070  00753643  20210513
1971          텔라움  047730  00304401  20210506
1972      뉴파워프라즈마  144960  00521390  20210602
1973     에이디테크놀로지  200710  00657002  20210602
1974        엘브이엠씨  900140  00838500  20210611

[1975 rows x 4 columns]

In [ ]:
# 종목코드의 기업명 불러낼 dict 만들기

corp_dict = {}

for i in range(len(df2['종목코드'])):
    corp_dict[df2.loc[i]['종목코드']] = str(df2.loc[i]['종목명'])

In [ ]:
com_code = df2['종목코드'][:100]

In [ ]:
# for i in 종목코드:
#     globals()['df{}'.format(★종목명 or ★종목코드)] = pd.DataFrame()

In [ ]:
page_number_lst = []  # 18페이지 까지 돌리기
for i in range(10):
    page_number_lst.append(i+1)

In [ ]:
# page_number_lst = np.arange(1,10) # 시작 페이지 ~ 끝 페이지 넘버 array

a = [1,2,3,4,5]

In [ ]:
#############수정용



# page_number_lst = [1, 2, 3, 4, 5] 

list_date = []
list_endprice = []
corp_total = []
corp_name = []

for code in com_code:
    try:
        for _page in page_number_lst: # 1페이지부터 n페이지까지 크롤링

            df = pd.DataFrame()

            url_head = 'https://finance.naver.com/item/sise_day.nhn?code=361610&page={}'.format(_page)
            headers = {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}

            web = requests.get(url_head, headers = headers).content #자료 요청
            soup = BeautifulSoup( web, 'html.parser') # html 파싱

            for tr in soup.find('table').find_all('tr'):
                try:
                    if len(tr.find_all("td")[0].get_text()) != 10: # 날짜가 비워진 셀은 패스 
                        pass
                    else:
                        if tr.find_all("td")[0].get_text() in list_date : # 동일한 날짜가 기존에 있었는지 체크 (중복 페이지)
                            break
                        else:
                            list_date.append(tr.find_all("td")[0].get_text())
                            list_endprice.append(tr.find_all('td')[1].get_text())
                            corp_total.append(code)
                            corp_name.append(corp_dict[code])

                        for i in range(len(quote_cp)):
                            quote_cp[i] = quote_cp[i].replace(",","")
                        quote_cp = list(map(int,quote_cp))
                except:
                    pass
        time.sleep(3)
    except:
        pass

In [ ]:
len(data_1)

In [ ]:
data_2

In [34]:
#############수정용

url_head = 'https://finance.naver.com/item/sise_day.nhn?code='
url_tail = '&page='
########################################### for문 들여쓰기######################



quote_cp = []
date_total = []
corp_total = []
corp_name = []
df = pd.DataFrame()

headers = {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}

for code in com_code:
    try:
        for _page in page_number_lst: # 1페이지부터 n페이지까지 크롤링
            web = requests.get(url_head + code +url_tail+str(_page), headers = headers).content #자료 요청
            soup = BeautifulSoup( web, 'html.parser') # html 파싱
            date_ = soup.find_all('td', {'align': 'center'}) # 파싱한 부분에서 날짜 부분
            quote = soup.find_all('td', {'class': 'num'}) # 파싱한 부분에서 종가 부분


            for i in range( len(date_) ):
                if date_[i].get_text() not in date_total and quote[i*6].get_text() not in quote_cp:
                    date_total.append(date_[i].get_text())
                    quote_cp.append(quote[i*6].get_text())
                    corp_total.append(code)
                    corp_name.append(corp_dict[code])


            for i in range(len(quote_cp)):
                quote_cp[i] = quote_cp[i].replace(",","")
            quote_cp = list(map(int,quote_cp))
    except:
        print("에러난 종목코드는 : {}입니다.".format(code))
        pass
########################################### for문 들여쓰기######################
df['날짜'] = date_total
df['주식_종가'] = quote_cp
df['종목코드'] = corp_total
df['종목명'] = corp_name
df

에러난 종목코드는 : 069080입니다.
에러난 종목코드는 : 115440입니다.
에러난 종목코드는 : 305090입니다.
에러난 종목코드는 : 187790입니다.
에러난 종목코드는 : 066910입니다.
에러난 종목코드는 : 042600입니다.
에러난 종목코드는 : 051380입니다.
에러난 종목코드는 : 160600입니다.
에러난 종목코드는 : 225430입니다.
에러난 종목코드는 : 331520입니다.
에러난 종목코드는 : 086220입니다.
에러난 종목코드는 : 215100입니다.
에러난 종목코드는 : 069730입니다.
에러난 종목코드는 : 355150입니다.
에러난 종목코드는 : 339950입니다.
에러난 종목코드는 : 233250입니다.
에러난 종목코드는 : 357250입니다.
에러난 종목코드는 : 101680입니다.
에러난 종목코드는 : 318410입니다.
에러난 종목코드는 : 122350입니다.
에러난 종목코드는 : 245450입니다.
에러난 종목코드는 : 033270입니다.
에러난 종목코드는 : 263860입니다.
에러난 종목코드는 : 033540입니다.
에러난 종목코드는 : 015360입니다.
에러난 종목코드는 : 025320입니다.
에러난 종목코드는 : 012690입니다.
에러난 종목코드는 : 004870입니다.
에러난 종목코드는 : 264660입니다.
에러난 종목코드는 : 004450입니다.
에러난 종목코드는 : 035150입니다.
에러난 종목코드는 : 239890입니다.
에러난 종목코드는 : 215050입니다.
에러난 종목코드는 : 003380입니다.
에러난 종목코드는 : 096630입니다.
에러난 종목코드는 : 001360입니다.
에러난 종목코드는 : 133820입니다.
에러난 종목코드는 : 006250입니다.
에러난 종목코드는 : 214270입니다.
에러난 종목코드는 : 023460입니다.
에러난 종목코드는 : 033020입니다.
에러난 종목코드는 : 052710입니다.
에러난 종목코드는 : 065570입니다.
에러난 종목코드는 : 086710입니다.
에러난 종목코드는 : 285130입니다.
에러난 종목코드는 : 029780입니다.
에러난 종목코드는 : 290510입니다.
에러난 종목코드는 : 084690입니다.
에러난 종목코드는 : 032540입니다.
에러난 종목코드는 : 196300입니다.
에러난 종목코드는 : 347890입니다.
에러난 종목코드는 : 000540입니다.
에러난 종목코드는 : 017250입니다.
에러난 종목코드는 : 321260입니다.
에러난 종목코드는 : 331380입니다.
에러난 종목코드는 : 298060입니다.
에러난 종목코드는 : 096040입니다.
에러난 종목코드는 : 350520입니다.
에러난 종목코드는 : 272290입니다.
에러난 종목코드는 : 142760입니다.
에러난 종목코드는 : 081970입니다.
에러난 종목코드는 : 010660입니다.
에러난 종목코드는 : 104830입니다.
에러난 종목코드는 : 228180입니다.
에러난 종목코드는 : 096640입니다.
에러난 종목코드는 : 003000입니다.
에러난 종목코드는 : 053210입니다.
에러난 종목코드는 : 083930입니다.
에러난 종목코드는 : 140660입니다.
에러난 종목코드는 : 034830입니다.
에러난 종목코드는 : 134380입니다.
에러난 종목코드는 : 044990입니다.
에러난 종목코드는 : 085660입니다.
에러난 종목코드는 : 081000입니다.
에러난 종목코드는 : 363280입니다.
에러난 종목코드는 : 092870입니다.
에러난 종목코드는 : 072020입니다.
에러난 종목코드는 : 244880입니다.
에러난 종목코드는 : 058480입니다.
에러난 종목코드는 : 311060입니다.
에러난 종목코드는 : 318010입니다.
에러난 종목코드는 : 040610입니다.
에러난 종목코드는 : 163560입니다.
에러난 종목코드는 : 115610입니다.
에러난 종목코드는 : 211050입니다.
에러난 종목코드는 : 037350입니다.
에러난 종목코드는 : 222980입니다.
에러난 종목코드는 : 191410입니다.
에러난 종목코드는 : 155900입니다.
에러난 종목코드는 : 143240입니다.
에러난 종목코드는 : 340350입니다.
에러난 종목코드는 : 317690입니다.
에러난 종목코드는 : 293780입니다.
에러난 종목코드는 : 348350입니다.
에러난 종목코드는 : 067160입니다.
에러난 종목코드는 : 323350입니다.
에러난 종목코드는 : 036710입니다.
에러난 종목코드는 : 222800입니다.
에러난 종목코드는 : 304100입니다.

            날짜   주식_종가    종목코드      종목명
0   2021.06.21   36450  314130   지놈앤컴퍼니
1   2021.06.18   37350  314130   지놈앤컴퍼니
2   2021.06.17   36850  314130   지놈앤컴퍼니
3   2021.06.16   36500  314130   지놈앤컴퍼니
4   2021.06.15   34600  314130   지놈앤컴퍼니
5   2021.06.14   34400  314130   지놈앤컴퍼니
6   2021.06.11   34850  314130   지놈앤컴퍼니
7   2021.06.10   34550  314130   지놈앤컴퍼니
8   2021.06.09   34150  314130   지놈앤컴퍼니
9   2021.06.08   34950  314130   지놈앤컴퍼니
10                      006250     극동전선
11  2005.07.14  24,250  006250     극동전선
12  2005.07.13  24,200  006250     극동전선
13  2005.07.08  24,400  006250     극동전선
14  2005.07.07  24,150  006250     극동전선
15  2005.07.06  23,750  006250     극동전선
16  2004.12.16     850  033020     세아메탈
17  2004.12.08     900  033020     세아메탈
18  2018.10.08   1,350  081970      넥스지
19  2018.10.05   1,265  081970      넥스지
20  2018.10.04   1,450  081970      넥스지
21  2018.10.02   1,230  081970      넥스지
22  2018.10.01   1,110  081970      넥스지
23  2018.09.28   1,015  081970      넥스지
24  2018.09.27  10,450  081970      넥스지
25  2020.08.05  15,750  228180  티씨엠생명과학
26  2010.05.06     110  058480    해원에스티
27  2010.05.03     105  058480    해원에스티
28  2010.04.28     120  058480    해원에스티
29  2010.04.27     600  058480    해원에스티

In [11]:
#############수정용

url_head = 'https://finance.naver.com/item/sise_day.nhn?code='
url_tail = '&page='
########################################### for문 들여쓰기######################



quote_cp = []
date_total = []
corp_total = []
corp_name = []
df = pd.DataFrame()

headers = {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}
try:
    for code in com_code:

        for _page in page_number_lst:

            web = requests.get(url_head + code +url_tail+str(_page), headers = headers).content #자료 요청
            soup = BeautifulSoup( web, 'html.parser') # html 파싱
            date_ = soup.find_all('td', {'align': 'center'}) # 파싱한 부분에서 날짜 부분
            quote = soup.find_all('td', {'class': 'num'}) # 파싱한 부분에서 날짜 부분


            for i in range( len(date_) ):
                if date_[i].get_text() not in date_total:
                    date_total.append(date_[i].get_text())
                corp_total.append(code)
                corp_name.append(corp_dict[code])
                
            for i in range( len(quote) ):
                if i%6 == 0:
                    quote_cp.append(quote[i].get_text())

    for i in range(len(quote_cp)):
        quote_cp[i] = quote_cp[i].replace(",","")
    quote_cp = list(map(int,quote_cp))
except:
    pass
########################################### for문 들여쓰기######################
df['날짜'] = date_total
df['주식_종가'] = quote_cp
df['종목코드'] = corp_total
df['종목명'] = corp_name
df

ValueError: Length of values does not match length of index

ValueError: No group keys passed!